name: InteriorKits
main: com.boveybrawlers.InteriorKits.InteriorKits
version: 0.5
commands:
    head:
        description: Gives a player a player-owned skull and records this for the top kit
        usage: /head
        aliases: [skull]
    ikit:
        description: Gives a player the 9 top player-owner skulls for interior decoration
        usage: /ikit
        aliases: [interior]